/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ishika.guessinggame;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author ishika jain
 */
public class Gui extends javax.swing.JFrame {

    
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }
    
    int bestScore=0, yourScore=0,addCorrectScore=0;
    byte guessCount=0,errorCount=0,yourGuesses=0;
    int random_number,lives=5;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Score = new javax.swing.JLabel();
        guesses = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        guessedNumber = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Number Guessing Game");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 298, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 431, 10));

        Score.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score.setText("Score : 0");
        Score.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 65, 31));

        guesses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guesses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guesses.setText("Guesses : 0");
        guesses.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(guesses, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 69, 31));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Enter your guess :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 128, 26));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        guessedNumber.setColumns(20);
        guessedNumber.setRows(5);
        guessedNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        guessedNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guessedNumberKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(guessedNumber);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 68, 35));

        jButton1.setText("New Random Number");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 38));

        jButton2.setText("Guess");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 170, 38));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 153, 114, -1));

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setToolTipText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 160, 114, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Random r = new Random();
        random_number = (int)Math.round(Math.random()*100);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        int num = Integer.parseInt(guessedNumber.getText());
        if(guessedNumber.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your number!");
        }else if(Integer.parseInt(guessedNumber.getText())>=101){
            JOptionPane.showMessageDialog(null, "Please enter number between 0-100!");    
        }else{
            if(num==random_number){
                JOptionPane.showMessageDialog(null, "Correct guess!");
                yourScore++;
                Score.setText("Score: "+yourScore);
            }else if(num>random_number){
                JOptionPane.showMessageDialog(null, "Number is greater than the actual number.");
                errorCount--;
                
            }else{
                JOptionPane.showMessageDialog(null, "Number is smaller than the actual number.");
                errorCount--;
            }
            yourGuesses++;
            guesses.setText("Guess: "+yourGuesses);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void guessedNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guessedNumberKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            guessedNumber.setEditable(false);
            jLabel8.setText("Please enter number only!");
        }
        else{
            guessedNumber.setEditable(true);
        }
    }//GEN-LAST:event_guessedNumberKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Score;
    private javax.swing.JTextArea guessedNumber;
    private javax.swing.JLabel guesses;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
